---
## add all members of a group. Separate file for nested loop
- name: add group's members
  user:
    name: "{{ item }}"
    groups: "{{ current_group.name }}"
    append: yes
  loop: "{{ current_group.members }}"
  when: current_group.members is defined and current_group.members|length > 0 