---
## add all members of a group. Separate file for nested loop
- name: add group's members
  user:
    name: "{{ member }}"
    groups: "{{ os_group.name }}"
    append: yes
  loop: "{{ os_group.members }}"
  loop_control:
    loop_var: member
  when: os_group.members is defined and os_group.members|length > 0 